"""Command-line interface for the Frozen Test v2 reconciliation and sealing pipeline.

Subcommands:

  validate   validate the four input documents and report the reconciliation summary
  reconcile  export the human-adjudication worksheet and a decisions template
  seal       apply human decisions and seal the benchmark with a lock manifest
  verify     recompute hashes and leakage checks for a sealed directory

Every command is offline and never invokes Phi4, ANEX, scope policy v2, or the
schedule validator.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Mapping

from .blinding import REMOVED_GROUP_KEYS, blind_benchmark
from .contract import CONTRACT_PROFILES, DEFAULT_CONTRACT, get_profile
from .decisions import SealRefusal, apply_decisions
from .documents import DocumentFormatError, canonical_json, load_json_document, write_text
from .reconcile import Reconciliation, ReconciliationError, reconcile
from .seal import (
    DEFAULT_MAX_SAME_ACTION_RUN,
    DEFAULT_SHUFFLE_SEED,
    resolve_source_commit,
    seal,
    verify_sealed_directory,
)

RECONCILE_FILENAMES: dict[str, str] = {
    "worksheet_json": "reconciliation_worksheet.json",
    "worksheet_markdown": "reconciliation_worksheet.md",
    "decisions_template": "human_decisions_template.json",
}


def _emit(payload: dict[str, Any]) -> None:
    print(json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False))


def _failure(status: str, problems: list[str]) -> int:
    _emit({"status": status, "problems": list(problems)})
    return 1


def _add_input_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--batch-a", required=True, help="benchmark JSON generated by model A")
    parser.add_argument("--review-of-a", required=True,
                        help="model B's blind review of batch A")
    parser.add_argument("--batch-b", required=True, help="benchmark JSON generated by model B")
    parser.add_argument("--review-of-b", required=True,
                        help="model A's blind review of batch B")
    parser.add_argument("--tolerate-leading-prose", action="store_true",
                        help="extract the JSON payload that follows leading prose and record "
                             "the defect in the worksheet and manifest instead of failing")
    parser.add_argument("--topology-catalogue",
                        help="JSON object mapping topology_id to working_period and "
                             "communication_range (default: legacy30_seed7 only)")
    parser.add_argument("--contract", choices=sorted(CONTRACT_PROFILES),
                        default=DEFAULT_CONTRACT.version,
                        help="configuration contract profile: frozen-test-v3 fixes "
                             "interference_ratio at 1.0 (default); frozen-test-v2 reproduces "
                             "the rules the sealed Frozen Test v2 was adjudicated under")


def _load_catalogue(path: str | None) -> dict[str, Any] | None:
    if not path:
        return None
    document = load_json_document(path)
    if not isinstance(document.data, dict) or not document.data:
        raise DocumentFormatError(f"{path}: topology catalogue must be a non-empty object")
    return document.data


def _load_reconciliation(args: argparse.Namespace) -> Reconciliation:
    tolerate = bool(args.tolerate_leading_prose)
    documents = [
        load_json_document(path, tolerate_leading_prose=tolerate)
        for path in (args.batch_a, args.review_of_a, args.batch_b, args.review_of_b)
    ]
    return reconcile(*documents, catalogue=_load_catalogue(args.topology_catalogue),
                     profile=get_profile(args.contract))


def cmd_validate(args: argparse.Namespace) -> int:
    try:
        reconciliation = _load_reconciliation(args)
    except DocumentFormatError as exc:
        return _failure("invalid", [str(exc)])
    except ReconciliationError as exc:
        return _failure("invalid", exc.problems)
    _emit({
        "status": "valid",
        "summary": reconciliation.summary(),
        "batch_warnings": {batch.batch_id: batch.warnings for batch in reconciliation.batches},
    })
    return 0


def cmd_reconcile(args: argparse.Namespace) -> int:
    try:
        reconciliation = _load_reconciliation(args)
    except DocumentFormatError as exc:
        return _failure("invalid", [str(exc)])
    except ReconciliationError as exc:
        return _failure("invalid", exc.problems)
    output_dir = Path(args.out)
    paths = {key: output_dir / name for key, name in RECONCILE_FILENAMES.items()}
    existing = [str(path) for path in paths.values() if path.exists()]
    if existing and not args.overwrite:
        return _failure("refused", [f"output exists (pass --overwrite to replace): {path}"
                                    for path in existing])
    output_dir.mkdir(parents=True, exist_ok=True)
    write_text(paths["worksheet_json"], canonical_json(reconciliation.worksheet()),
               overwrite=args.overwrite)
    write_text(paths["worksheet_markdown"], reconciliation.markdown(), overwrite=args.overwrite)
    write_text(paths["decisions_template"], canonical_json(reconciliation.decisions_template()),
               overwrite=args.overwrite)
    _emit({
        "status": "reconciled",
        "summary": reconciliation.summary(),
        "batch_warnings": {batch.batch_id: batch.warnings for batch in reconciliation.batches},
        "outputs": {key: str(path) for key, path in paths.items()},
    })
    return 0


def _parse_prompt(spec: str) -> tuple[str, Path]:
    name, separator, path = spec.partition("=")
    if not separator or not name.strip() or not path.strip():
        raise argparse.ArgumentTypeError("expected NAME=PATH")
    return name.strip(), Path(path.strip())


def _parse_topology_file(spec: str) -> tuple[str | None, Path]:
    """Accept ``ID=PATH`` or a bare ``PATH`` (named by --topology-id)."""
    name, separator, path = spec.partition("=")
    if not separator:
        return None, Path(spec.strip())
    if not name.strip() or not path.strip():
        raise argparse.ArgumentTypeError("expected TOPOLOGY_ID=PATH or PATH")
    return name.strip(), Path(path.strip())


def _topology_files(args: argparse.Namespace,
                    catalogue: Mapping[str, Any]) -> dict[str, Path]:
    """Map explicit topology files to catalogue ids; unnamed paths need an id."""
    files: dict[str, Path] = {}
    for name, path in args.topology_file:
        if name is None:
            name = args.topology_id
            if name is None:
                if len(catalogue) != 1:
                    raise DocumentFormatError(
                        f"--topology-file {path} needs a topology id: pass "
                        "TOPOLOGY_ID=PATH or --topology-id because the catalogue holds "
                        f"{len(catalogue)} topologies")
                name = next(iter(catalogue))
        if name in files:
            raise DocumentFormatError(f"two topology files supplied for {name!r}")
        files[name] = path
    return files


def cmd_seal(args: argparse.Namespace) -> int:
    try:
        reconciliation = _load_reconciliation(args)
        decisions = load_json_document(args.decisions)
        model_metadata = load_json_document(args.model_metadata)
        source_commit = resolve_source_commit(args.project_root, args.source_commit)
        result = seal(
            reconciliation=reconciliation,
            decisions=decisions,
            model_metadata=model_metadata,
            prompt_files=dict(args.prompt),
            topology_files=_topology_files(args, reconciliation.catalogue),
            catalogue_dir=args.catalogue_dir,
            policy_version=args.policy_version,
            output_dir=args.out,
            source_commit=source_commit,
            source_archives=args.source_archive,
            shuffle_seed=args.shuffle_seed,
            max_same_action_run=args.max_same_action_run,
        )
    except DocumentFormatError as exc:
        return _failure("refused", [str(exc)])
    except ReconciliationError as exc:
        return _failure("refused", exc.problems)
    except SealRefusal as exc:
        return _failure("refused", exc.problems)
    _emit({
        "status": "sealed",
        "output_dir": str(result.output_dir),
        "manifest": str(result.paths["manifest"]),
        "counts": result.manifest["counts"],
        "quotas": result.manifest["quotas"],
        "outputs": result.manifest["outputs"],
    })
    return 0


def cmd_check_decisions(args: argparse.Namespace) -> int:
    """Apply the decisions in memory and report what sealing would refuse on."""
    try:
        reconciliation = _load_reconciliation(args)
        decisions = load_json_document(args.decisions)
        final_set = apply_decisions(reconciliation, decisions.data)
    except DocumentFormatError as exc:
        return _failure("refused", [str(exc)])
    except ReconciliationError as exc:
        return _failure("refused", exc.problems)
    except SealRefusal as exc:
        return _failure("refused", exc.problems)
    _emit({
        "status": "decisions_accepted",
        "decided_by": final_set.decided_by,
        "decisions_applied": final_set.decisions_applied,
        "excluded_groups": final_set.excluded,
        "kept_groups": len(final_set.groups),
        "per_action": final_set.quotas_observed,
        "quota_source": final_set.quota_source,
    })
    return 0


def cmd_blind(args: argparse.Namespace) -> int:
    """Write the reviewer-facing copy of a generator batch (ids and texts only)."""
    output = Path(args.out)
    if output.exists():
        return _failure("refused", [f"output exists: {output}"])
    try:
        document = load_json_document(args.benchmark,
                                      tolerate_leading_prose=bool(args.tolerate_leading_prose))
        blinded = blind_benchmark(document.data)
    except (DocumentFormatError, ValueError) as exc:
        return _failure("refused", [str(exc)])
    output.parent.mkdir(parents=True, exist_ok=True)
    write_text(output, canonical_json(blinded))
    _emit({
        "status": "blinded",
        "output": str(output),
        "groups": blinded["self_check"]["group_count"],
        "items": blinded["self_check"]["item_count"],
        "removed_fields": list(REMOVED_GROUP_KEYS),
        "source_sha256": document.sha256,
    })
    return 0


def cmd_verify(args: argparse.Namespace) -> int:
    report = verify_sealed_directory(args.sealed_dir)
    _emit({"status": "verified" if report["valid"] else "invalid", **report})
    return 0 if report["valid"] else 1


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="python -m frozen_test_v2", description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    subparsers = parser.add_subparsers(dest="command", required=True)

    validate = subparsers.add_parser("validate", help="validate inputs and summarize agreement")
    _add_input_arguments(validate)
    validate.set_defaults(handler=cmd_validate)

    reconcile_parser = subparsers.add_parser(
        "reconcile", help="export the human-adjudication worksheet and decisions template")
    _add_input_arguments(reconcile_parser)
    reconcile_parser.add_argument("--out", required=True, help="directory for worksheet files")
    reconcile_parser.add_argument("--overwrite", action="store_true",
                                  help="replace existing worksheet files")
    reconcile_parser.set_defaults(handler=cmd_reconcile)

    seal_parser = subparsers.add_parser("seal", help="apply human decisions and seal")
    _add_input_arguments(seal_parser)
    seal_parser.add_argument("--decisions", required=True, help="human decisions JSON")
    seal_parser.add_argument("--out", required=True,
                             help="output directory (must not contain a sealed benchmark)")
    seal_parser.add_argument("--model-metadata", required=True,
                             help="JSON with model_a and model_b metadata (model_id, ...)")
    seal_parser.add_argument("--prompt", action="append", default=[], type=_parse_prompt,
                             metavar="NAME=PATH", help="prompt file to hash (repeatable)")
    seal_parser.add_argument("--topology-file", action="append", default=[],
                             type=_parse_topology_file, metavar="TOPOLOGY_ID=PATH",
                             help="topology JSON to hash, repeatable. A bare PATH is allowed "
                                  "when the catalogue holds one topology or --topology-id "
                                  "names it. Every catalogue topology not given here must "
                                  "carry a 'path' in its catalogue entry")
    seal_parser.add_argument("--topology-id", default=None,
                             help="id for a bare --topology-file path")
    seal_parser.add_argument("--catalogue-dir", default=None,
                             help="directory relative paths in the catalogue resolve against "
                                  "(default: the working directory)")
    seal_parser.add_argument("--policy-version", required=True,
                             help="scope policy version string recorded in the manifest")
    seal_parser.add_argument("--source-commit",
                             help="explicit source commit or archive identifier")
    seal_parser.add_argument("--project-root",
                             help="git checkout used to resolve the source commit when "
                                  "--source-commit is not given")
    seal_parser.add_argument("--source-archive", action="append", default=[],
                             help="source archive to hash into the manifest (repeatable)")
    seal_parser.add_argument("--shuffle-seed", type=int, default=DEFAULT_SHUFFLE_SEED)
    seal_parser.add_argument("--max-same-action-run", type=int,
                             default=DEFAULT_MAX_SAME_ACTION_RUN)
    seal_parser.set_defaults(handler=cmd_seal)

    check = subparsers.add_parser(
        "check-decisions",
        help="apply a human-decisions file in memory and report what sealing would refuse on")
    _add_input_arguments(check)
    check.add_argument("--decisions", required=True, help="human decisions JSON")
    check.set_defaults(handler=cmd_check_decisions)

    blind = subparsers.add_parser(
        "blind", help="write the reviewer-facing copy of a generator batch (ids and texts only)")
    blind.add_argument("--benchmark", required=True, help="generator batch JSON")
    blind.add_argument("--out", required=True, help="blind copy to create (write-once)")
    blind.add_argument("--tolerate-leading-prose", action="store_true",
                       help="extract the JSON payload that follows leading prose")
    blind.set_defaults(handler=cmd_blind)

    verify = subparsers.add_parser("verify", help="verify a sealed directory")
    verify.add_argument("--sealed-dir", required=True)
    verify.set_defaults(handler=cmd_verify)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    return int(args.handler(args))
