#!/usr/bin/env python3
"""Render the paper's figures as LaTeX, from the exported figure data.

Drawn in pgfplots rather than as an image, for three reasons: the type matches
the body text, the numbers come from the data file rather than from a drawing
program, and a reviewer reading the PDF can select the labels.

The one thing a bar chart cannot show is a bar of height zero, which is exactly
the value this figure exists to communicate. The zero is therefore drawn as a
labelled tick on the axis rather than left to disappear.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Mapping

GATE = "caught by the scope gate"
AGENT = "caught by the ungated agent"
NAMED = "names the capability"
COMPOSED = "composes it from ordinary words"
# Tick labels only; the keys above must keep matching the figure data.
NAMED_TICK = "names it"
COMPOSED_TICK = "composes it"


def fraction(part: int, whole: int) -> float:
    return part / whole if whole else 0.0


def render_phrasing(data: Mapping[str, Any]) -> str:
    series = data["series"]
    named, composed = series[NAMED], series[COMPOSED]
    rows = [
        ("gate", named["items"], named[GATE], composed["items"], composed[GATE]),
        ("agent", named["items"], named[AGENT], composed["items"], composed[AGENT]),
    ]

    def plot(label: str, style: str) -> str:
        row = next(r for r in rows if r[0] == label)
        _, named_items, named_value, composed_items, composed_value = row
        return (
            f"\\addplot[{style}] coordinates {{"
            f"(0,{fraction(named_value, named_items):.4f}) "
            f"(1,{fraction(composed_value, composed_items):.4f})}};"
        )

    # Counts printed on or beside each bar, so the figure is readable without
    # reading the axis.
    labels = []
    for index, (group, items_key) in enumerate(((named, NAMED), (composed, COMPOSED))):
        for offset, (key, style) in enumerate(((GATE, "gatebar"), (AGENT, "agentbar"))):
            value = group[key]
            height = fraction(value, group["items"])
            shift = -0.17 if offset == 0 else 0.17
            anchor = "south" if height > 0.06 else "south"
            # The gate is deterministic, so its count is an integer; the agent
            # decodes at temperature 1 and its count is the mean of the repeats,
            # which is a decimal whenever they disagreed.
            shown = f"{value:g}" if float(value).is_integer() else f"{value:.1f}"
            labels.append(
                f"\\node[font=\\footnotesize,anchor={anchor},inner sep=1.5pt] "
                f"at (axis cs:{index + shift},{height:.4f}) "
                f"{{{shown}/{group['items']}}};")

    zero_marks = []
    for index, group in enumerate((named, composed)):
        if group[GATE] == 0:
            zero_marks.append(
                f"\\draw[very thick] (axis cs:{index - 0.30},0) -- "
                f"(axis cs:{index - 0.04},0);")

    return "\n".join([
        "% Generated by scripts/render_figures.py. Do not edit.",
        "% Source: figure_data/fig2_phrasing.json",
        r"\begin{figure}[tb]",
        r"\centering",
        r"\begin{tikzpicture}",
        r"\begin{axis}[",
        r"  width=0.96\columnwidth, height=0.36\columnwidth,",
        r"  ybar, bar width=11pt, enlarge x limits=0.30,",
        # A ybar legend draws the plot mark as well as the bar, which reads as
        # two hollow boxes. Draw one filled square instead.
        r"  legend image code/.code={\draw[##1] (0cm,-0.08cm) rectangle "
        r"(0.30cm,0.16cm);},",
        r"  ymin=0, ymax=1.34, ytick={0,0.25,0.5,0.75,1},",
        r"  yticklabels={0,.25,.5,.75,1},",
        r"  ylabel={recall on unsupported requests},",
        r"  ylabel style={font=\small},",
        r"  xtick={0,1},",
        f"  xticklabels={{{{{NAMED_TICK}}},{{{COMPOSED_TICK}}}}},",
        r"  xticklabel style={font=\small},",
        r"  yticklabel style={font=\footnotesize},",
        r"  axis lines*=left, axis line style={-},",
        r"  tick style={draw=none}, ymajorgrids=false,",
        r"  legend style={draw=none, font=\footnotesize, at={(0.5,1.02)},",
        r"    anchor=south, legend columns=2, column sep=1.2em},",
        r"]",
        plot("gate", "gatebar"),
        plot("agent", "agentbar"),
        r"\legend{scope gate, agent with the gate removed}",
        *zero_marks,
        *labels,
        r"\end{axis}",
        r"\end{tikzpicture}",
        r"\caption{Recall on the 72 gold-\textsc{unsupported} requests, split by",
        r"whether the request names the capability it asks for. The gate's bars",
        r"are one number, the agent's the mean of three repeats. Request ids are",
        r"in \texttt{figure\_data/fig2\_phrasing.json}.}",
        r"\label{fig:phrasing}",
        # The class checks for this and warns without it, and a bar chart is
        # exactly the figure a screen reader cannot recover from the caption:
        # the caption says what the split means, the description says what the
        # four bars are.
        r"\Description{A bar chart with two groups of two bars, recall on the",
        r"vertical axis from zero to one. On the left, the 26 unsupported",
        r"requests that name the capability they ask for: the scope gate reaches",
        r"0.42, eleven of them, and the agent with the gate removed reaches 1.0,",
        r"all twenty-six. On the right, the 46 that express the capability",
        r"without naming it: the gate reaches zero, marked with a written zero,",
        r"and the agent 0.97, a mean 44.7 of 46 over three repeats.}",
        r"\end{figure}",
        "",
    ])


def render_direct(data: Mapping[str, Any]) -> str:
    """Every certified direct schedule against the solver's, on a log axis.

    The axis is logarithmic because the quantity spans 1.4 to 789: on a linear
    axis the ten small penalties collapse onto the floor and only the 300-node
    point is legible, which would hide that the degradation is orderly rather
    than one outlier.
    """
    points = data["points"]
    coords = " ".join(f"({p['nodes']},{p['penalty']})" for p in points)
    worst = max(points, key=lambda p: p["penalty"])
    valid = data["validity"]
    return "\n".join([
        r"% Generated by scripts/render_figures.py. Do not edit.",
        r"% Source: figure_data/fig4_direct.json",
        r"\begin{figure}[tb]",
        r"\centering",
        r"\begin{tikzpicture}",
        r"\begin{axis}[",
        r"  width=0.96\columnwidth, height=0.42\columnwidth,",
        r"  ymode=log, log basis y=10,",
        r"  xlabel={nodes}, ylabel={span $\div$ solver's span},",
        r"  xlabel style={font=\small}, ylabel style={font=\small},",
        r"  ticklabel style={font=\scriptsize},",
        r"  xmin=0, xmax=330, ymin=1, ymax=2000,",
        r"  ytick={1,10,100,1000}, yticklabels={$1\times$,$10\times$,"
        r"$100\times$,$1000\times$},",
        r"  axis lines*=left, axis line style={-}, tick style={draw=none},",
        r"  ymajorgrids=true, grid style={draw=black!12},",
        r"]",
        r"\addplot[only marks, mark=*, mark size=1.7pt, draw=black, "
        r"fill=black!55] coordinates {" + coords + r"};",
        r"\addplot[no marks, dashed, draw=black!45] coordinates "
        r"{(0,1) (330,1)};",
        rf"\node[font=\scriptsize, anchor=east] at "
        rf"(axis cs:{worst['nodes'] - 12},{worst['penalty']}) "
        rf"{{{worst['penalty']:.0f}$\times$}};",
        r"\end{axis}",
        r"\end{tikzpicture}",
        rf"\caption{{What a certified schedule is worth. Each point is one of "
        rf"the {valid['valid']} direct-generation schedules the independent "
        rf"validator accepted, plotted as its span divided by the solver's on "
        rf"the same request; the dashed line is the solver. Validity is not "
        rf"the issue --- every point is certified --- but the penalty grows "
        rf"with the network, from {min(p['penalty'] for p in points):.1f}"
        rf"$\times$ at thirty nodes to {worst['penalty']:.0f}$\times$ at "
        rf"three hundred. The remaining "
        rf"{valid['items'] - valid['valid']} of {valid['items']} produced no "
        rf"valid schedule at all and cannot appear here.}}",
        r"\label{fig:direct}",
        r"\Description{A log-scale scatter plot of eleven points. The ratio "
        r"of the model's schedule span to the solver's rises steadily with "
        r"network size, from about 1.4 at thirty nodes to 789 at three "
        r"hundred nodes.}",
        r"\end{figure}",
        "",
    ])


def render_scaling(data: Mapping[str, Any]) -> str:
    """The deterministic core over the whole topology-channel sweep."""
    series = data["series"]
    plots = []
    for channels in sorted(series, key=int):
        pts = series[channels]
        coords = " ".join(f"({p['nodes']},{p['latency_mean']})" for p in pts)
        shade = 100 - 11 * (int(channels) - 1)
        plots.append(rf"\addplot[no marks, draw=black!{shade}, thick] "
                     rf"coordinates {{{coords}}};")
        label = f"channels {channels}" if channels == "1" else channels
        plots.append(rf"\addlegendentry{{{label}}}")
    return "\n".join([
        r"% Generated by scripts/render_figures.py. Do not edit.",
        r"% Source: figure_data/fig5_scaling.json",
        r"\begin{figure}[tb]",
        r"\centering",
        r"\begin{tikzpicture}",
        r"\begin{axis}[",
        r"  width=0.96\columnwidth, height=0.42\columnwidth,",
        r"  xlabel={nodes}, ylabel={span (slots)},",
        r"  xlabel style={font=\small}, ylabel style={font=\small},",
        r"  ticklabel style={font=\scriptsize},",
        r"  xmin=20, xmax=310, ymin=0,",
        r"  axis lines*=left, axis line style={-}, tick style={draw=none},",
        r"  ymajorgrids=true, grid style={draw=black!12},",
        r"  legend style={draw=none, font=\footnotesize, at={(1.0,1.04)},",
        r"    anchor=south east, legend columns=7, column sep=0.2em},",
        r"  legend cell align=left,",
        r"]",
        *plots,
        r"\end{axis}",
        r"\end{tikzpicture}",
        rf"\caption{{The deterministic core, independent of the agent. Mean "
        rf"collection span against network size, one line per channel count "
        rf"(legend), over {data['configurations']} topology--channel "
        rf"configurations and {data['runs']} runs. The independent validator "
        rf"accepted every schedule in every configuration. Channels help most "
        rf"between one and three and flatten after that, which is why the "
        rf"request contract's default of two is not a limiting choice.}}",
        r"\label{fig:scaling}",
        r"\Description{Seven nearly parallel rising lines showing mean "
        r"collection span growing with network size from thirty to three "
        r"hundred nodes, with more channels giving a lower span and the "
        r"benefit shrinking as channels increase.}",
        r"\end{figure}",
        "",
    ])


def tex_escape(text: str) -> str:
    """Escape what LaTeX reads specially.

    Field names and topology ids in this project are full of underscores,
    which are a subscript in maths mode and an error in text mode.
    """
    for char in ('\\', '&', '%', '$', '#', '_', '{', '}'):
        text = text.replace(char, '\\' + char)
    return text


# Sampled from Figure 1 so the two figures read as one system: Figure 1 is the
# pipeline, Figure 2 is one request going through it, and a lane keeps its
# colour across both. Fills are pale and strokes dark, so the panels stay
# distinguishable in greyscale and to a colour-blind reader; colour repeats the
# lane labels rather than carrying meaning of its own.
LANE_A_FILL, LANE_A_LINE = "E9F0F8", "1F4A78"
LANE_B_FILL, LANE_B_LINE = "FDF0DB", "B0660C"
LANE_C_FILL, LANE_C_LINE = "E5F4EE", "0F6955"


def render_schedule(data: Mapping[str, Any]) -> str:
    """One request from the sentence to the certified result.

    The submission carries the compact form: what the user wrote, what the
    model read out of it, what the contract supplied, and what the
    deterministic stages returned. Figure~1 already explains the architecture,
    so this figure does not redraw the pre-checks; the 30-sensor schedule it
    produced is in the unabridged version, where there is room to label every
    slot legibly.
    """
    t = data["typed_request"]
    defaults = data.get("contract_defaults", {})
    read = {k: v for k, v in t.items() if k not in defaults or defaults[k] != v}
    supplied = {k: v for k, v in t.items() if k in defaults and defaults[k] == v}
    fmt = lambda d: ", ".join(f"\\texttt{{{tex_escape(k)}}}={tex_escape(str(v))}"
                              for k, v in d.items())

    # --- the tree, for the unabridged version only -------------------------
    parent = {e["sender"]: e["receiver"] for e in data["schedule"]}
    slot = {e["sender"]: e["slot"] for e in data["schedule"]}
    channel = {e["sender"]: e["channel"] for e in data["schedule"]}
    sink = data["sink"]
    depth = {sink: 0}
    def depth_of(n):
        if n not in depth:
            depth[n] = depth_of(parent[n]) + 1
        return depth[n]
    for n in parent:
        depth_of(n)
    children: dict[int, list[int]] = {}
    for n, r in parent.items():
        children.setdefault(r, []).append(n)
    for kids in children.values():
        kids.sort()
    position: dict[int, float] = {}
    cursor = [0.0]
    def assign(n):
        kids = children.get(n, [])
        if not kids:
            position[n] = cursor[0]; cursor[0] += 1.0
            return position[n]
        spots = [assign(k) for k in kids]
        position[n] = (spots[0] + spots[-1]) / 2
        return position[n]
    assign(sink)
    wide = max(position.values()) or 1.0
    span, row = 15.0, 1.15
    position = {n: x / wide * span - span / 2 for n, x in position.items()}
    place = lambda n: (position[n], -depth[n] * row)
    art = []
    for n in sorted(parent, key=lambda n: slot[n]):
        ax, ay = place(n); bx, by = place(parent[n])
        dash = "" if channel[n] == 1 else ", dashed"
        art.append(rf"\draw[draw=laneCline!65{dash}, line width=0.45pt, "
                   rf"-{{Stealth[length=1.4mm]}}] ({ax:.2f},{ay:.2f}) -- "
                   rf"({bx:.2f},{by:.2f}) node[pos=0.6, fill=white, "
                   rf"inner sep=0.4pt, font=\scriptsize] {{{slot[n]}}};")
    for n in sorted(depth):
        x, y = place(n)
        if n == sink:
            art.append(rf"\fill[laneCline] ({x:.2f},{y:.2f}) circle (2.6pt);")
            art.append(rf"\node[font=\small, text=laneCline, anchor=south, "
                       rf"yshift=3pt] at ({x:.2f},{y:.2f}) {{sink}};")
        else:
            art.append(rf"\draw[fill=white, draw=laneCline!75, line width=0.5pt] "
                       rf"({x:.2f},{y:.2f}) circle (2.1pt);")

    return "\n".join([
        r"% Generated by scripts/render_figures.py. Do not edit.",
        r"% Source: figure_data/fig6_trace.json",
        rf"\definecolor{{laneAline}}{{HTML}}{{{LANE_A_LINE}}}",
        rf"\definecolor{{laneBfill}}{{HTML}}{{{LANE_B_FILL}}}",
        rf"\definecolor{{laneBline}}{{HTML}}{{{LANE_B_LINE}}}",
        rf"\definecolor{{laneCfill}}{{HTML}}{{{LANE_C_FILL}}}",
        rf"\definecolor{{laneCline}}{{HTML}}{{{LANE_C_LINE}}}",
        r"\begin{figure}[tb]",
        r"\centering\small",
        r"\setlength{\fboxsep}{3.5pt}",
        r"\begin{tabular}{@{}p{0.945\columnwidth}@{}}",
        r"\textcolor{black!55}{\bfseries the request} \\[1pt]",
        r"\fbox{\parbox{0.90\columnwidth}{\itshape "
        + tex_escape(data["user_text"]) + r"}} \\[4pt]",
        r"\textcolor{laneBline}{\bfseries determined by the request} \\[1pt]",
        r"\fbox{\parbox{0.90\columnwidth}{\raggedright\hyphenpenalty=10000 "
        + fmt(read) + r"}} \\[4pt]",
        r"\textcolor{black!55}{\bfseries contract defaults, the request being"
        r" silent} \\[1pt]",
        r"\fbox{\parbox{0.90\columnwidth}{\raggedright\hyphenpenalty=10000 "
        + fmt(supplied) + r"}} \\[4pt]",
        r"\textcolor{laneCline}{\bfseries returned by the deterministic stages}"
        r" \\[1pt]",
        rf"\fbox{{\parbox{{0.90\columnwidth}}{{"
        rf"{len(data['schedule'])} transmissions over "
        rf"{data['latency_slots']} slots on {len(data['nodes'])} sensors; "
        rf"validator certificate valid, "
        rf"{data['certificate']['violations']} violations}}}}",
        r"\end{tabular}",
        rf"\caption{{One request end to end, from the released ledger "
        rf"({tex_escape(data['request_id'])} on "
        rf"\texttt{{{tex_escape(data['topology_id'])}}}, "
        rf"{data['cost']['model_calls']} model call, "
        rf"{data['cost']['wall_seconds']}\,s). The model returns the typed "
        rf"request, a proposed action and its tool approvals; of the seven "
        rf"contract fields, the sentence determines two "
        rf"and the other five are the defaults \texttt{{contract.py}} lists "
        rf"as \texttt{{DEFAULT\_FIELDS}}. It "
        rf"Every entry of the schedule it produced is in "
        rf"\texttt{{figure\_data/fig6\_trace.json}}.}}",
        r"\label{fig:trace}",
        r"\Description{Four stacked boxes: the user's one-sentence request; "
        r"the two contract fields that sentence determines; the five fields "
        r"left to the contract's documented defaults; and the result, 29 "
        r"transmissions over 26 slots on 30 sensors with a valid validator "
        r"certificate.}",
        r"\end{figure}",
        "",
        r"\iffull",
        r"\begin{figure*}[t]",
        r"\centering",
        r"\begin{tikzpicture}[x=0.95cm, y=1cm]",
        *art,
        r"\end{tikzpicture}",
        rf"\caption{{The schedule Figure~\ref{{fig:trace}} produced. Each "
        rf"circle is a sensor, placed by its depth in the \emph{{aggregation "
        rf"tree}} rather than at its position in the network; each arrow is "
        rf"that sensor's single transmission, the number on it is the slot "
        rf"the transmission occupies, and a solid arrow is channel~1 against "
        rf"a dashed channel~2. Slots are numbered from zero, so they run to "
        rf"{data['latency_slots'] - 1} for a {data['latency_slots']}-slot "
        rf"collection.}}",
        r"\label{fig:schedule}",
        r"\Description{Thirty sensors in five rows by depth in the "
        r"aggregation tree, a filled sink at the top, and twenty-nine arrows "
        r"pointing upwards, each labelled with its time slot.}",
        r"\end{figure*}",
        r"\fi",
        "",
    ])


def render_trace(data: Mapping[str, Any]) -> str:
    """One request carried end to end, as three stacked panels.

    Drawn as a figure rather than quoted in the body because the point is the
    hand-off: a sentence goes in, a typed request comes out of the model, and
    everything after that is deterministic. The item deliberately misses its
    own latency target, so the last panel shows the reporter saying so.
    """
    t, r = data["typed_request"], data["result"]
    fields = ", ".join(
        f"\\texttt{{{tex_escape(k)}}}={tex_escape(str(v))}" for k, v in t.items())
    met = "missed" if r["target_met"] is False else "met"
    return "\n".join([
        r"% Generated by scripts/render_figures.py. Do not edit.",
        r"% Source: figure_data/fig6_trace.json",
        r"\begin{figure}[tb]",
        r"\small",
        r"\setlength{\fboxsep}{4pt}",
        r"\noindent\textbf{1. What the user writes}\\[2pt]",
        r"\noindent\fbox{\parbox{0.955\columnwidth}{\itshape "
        + tex_escape(data["user_text"]) + r"}}\\[5pt]",
        r"\noindent\textbf{2. What the model returns} --- a typed request, "
        r"never a schedule\\[2pt]",
        r"\noindent\fbox{\parbox{0.955\columnwidth}{\scriptsize\raggedright "
        + fields + r"}}\\[5pt]",
        r"\noindent\textbf{3. What the deterministic stages produce}"
        r"\\[2pt]",
        r"\noindent\fbox{\parbox{0.955\columnwidth}{\scriptsize\raggedright "
        rf"{r['transmissions']} transmissions over {r['latency_slots']} slots "
        rf"on {r['nodes']} nodes; validator certificate "
        rf"\textbf{{valid}}, {data['certificate']['violations']} violations; "
        rf"latency target {r['target_slots']} slots \textbf{{{met}}}."
        r"}}",
        rf"\caption{{One request end to end, taken from the released ledger "
        rf"({data['request_id']} on \texttt{{{tex_escape(data['topology_id'])}}}, "
        rf"{data['cost']['model_calls']} model call, "
        rf"{data['cost']['wall_seconds']}\,s). The model's whole output is "
        rf"panel~2: seven contract fields and a decision. It never sees the "
        rf"topology and never writes a schedule. We chose an item whose "
        rf"target the schedule misses, because that is what the deterministic "
        rf"reporter has to say and the model has no opportunity to soften.}}",
        r"\label{fig:trace}",
        r"\Description{Three stacked boxes. The first holds the user's "
        r"sentence. The second holds seven typed contract fields returned by "
        r"the model. The third holds the schedule statistics, a valid "
        r"validator certificate, and a note that the latency target was "
        r"missed.}",
        r"\end{figure}",
        "",
    ])


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--figure-data", required=True,
                        help="directory holding the exported figure data")
    parser.add_argument("--out-dir", required=True)
    args = parser.parse_args()

    source = Path(args.figure_data) / "fig2_phrasing.json"
    data = json.loads(source.read_text(encoding="utf-8"))
    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)
    target = out / "fig2_phrasing.tex"
    target.write_text(render_phrasing(data), encoding="utf-8")
    extra = []
    for name, renderer in (("fig4_direct", render_direct),
                           ("fig5_scaling", render_scaling),
                           ("fig6_trace", render_schedule)):
        path = Path(args.figure_data) / f"{name}.json"
        if not path.exists():
            continue
        payload = json.loads(path.read_text(encoding="utf-8"))
        written = out / f"{name}.tex"
        written.write_text(renderer(payload), encoding="utf-8")
        extra.append(str(written))
    series = data["series"]
    print(json.dumps({
        "status": "rendered", "out": str(target), "source": str(source),
        "also": extra,
        "values": {group: {"items": series[group]["items"],
                           "gate": series[group][GATE],
                           "agent": series[group][AGENT]}
                   for group in (NAMED, COMPOSED)},
    }, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
